name: Invite Users
on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Invite user to organization
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v4.1.3
        with:
          script: |
            const response = await github.repos.listCollaborators({owner: context.repo.owner, repo: context.repo.repo})
            const teamIds = response.data.map(collaborator => collaborator.id )
            const { data: pullRequest } = await github.pulls.get({owner: context.repo.owner, repo: context.repo.repo, pull_number: context.payload.pull_request.number})
            const { data: user } = await github.users.getByUsername({username: context.payload.pull_request.user.login})
            if (pullRequest.merged) {
              const { data: invitation } = await github.teams.addOrUpdateMembershipForUserInOrg({
                org: context.repo.owner,
                team_slug: 'CN-ON',
                username: user.login
              })
              console.log(`Invited ${user.login} to contributors team.`)
            }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
